name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
        submodules: 'recursive'
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: 'arm64'
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # true => removed from image
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        PLATFORM=aarch64 docker build -t bshibley/edgebotic_amr_ros-aarch64 -f ./Dockerfile .
    - name: Tag & push the image
      run: |
        DATESTAMP=$(date +%s)
        docker tag edgebotic_amr_ros-aarch64:latest ${{ secrets.DOCKERHUB_USERNAME }}/edgebotic_amr_ros-aarch64:${DATESTAMP}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/edgebotic_amr_ros-aarch64:${DATESTAMP}
