name: Docker Image CI

on:
  push:
    branches: [ "ros2-serial" ]
  pull_request:
    branches: [ "ros2-serial" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # configure git to use SSH key for private repos
    - uses: webfactory/ssh-agent@v0.5.1 
      with:
        ssh-private-key: |
              ${{ secrets.EDGEBOTIC_AMR_SSH_PRIVATE_KEY }}
              ${{ secrets.ROS2_CONTROL_EDGEBOTIC_AMR_SSH_PRIVATE_KEY }}
    - uses: actions/checkout@v3
      with:
        lfs: true
        submodules: 'recursive'
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: 'arm64'
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        PLATFORM=aarch64 docker build -t edgebotic_amr_ros-aarch64 -f ./Dockerfile .
    - name: Tag & push the image
      run: |
        DATESTAMP=$(date +%s)
        docker tag edgebotic_amr_ros-aarch64:latest ${{ secrets.DOCKERHUB_USERNAME }}/edgebotic_amr_ros-aarch64:ros2-serial-${DATESTAMP}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/edgebotic_amr_ros-aarch64:ros2-serial-${DATESTAMP}
