name: Docker Image CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # configure git to use SSH key for private repos
    - uses: webfactory/ssh-agent@v0.5.1 
      with:
        ssh-private-key: |
              ${{ secrets.EDGEBOTIC_AMR_SSH_PRIVATE_KEY }}
              ${{ secrets.ROS2_CONTROL_EDGEBOTIC_AMR_SSH_PRIVATE_KEY }}
    - uses: actions/checkout@v3
      with:
        lfs: true
        submodules: 'recursive'
    - name: Get current date
      id: date
      run: |
        echo "{datestamp}={$(date +%s)}" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: 'arm64'
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
    - name: Cache register
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./
        platforms: linux/arm64
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        load: true
        tags: edgebotic_amr_ros-aarch64:${{ env.datestamp }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
